var PgTutorialVideo=function(e,t){var i,o,a,n,d,l,s,r,p,c,v,u,f,m=!0;m?(o=`https://pinegrowsites.com/@pine/vimeo-player/index.html?video_id=${e}&mode=normal`,pgIsDev()&&(o+="&z="+Math.random())):o=`https://player.vimeo.com/video/${e}?autoplay=1`;isApp()?pinegrow.showNotice(`<p>Due to recent changes on the side of our video hosting partner Vimeo, in app playback often fails. To avoid that, tutorial videos now open in a separate browser window.</p>`,"A note about playing videos","vimeo-video-player",function(){pinegrow.openExternalUrl(`https://vimeo.com/`+e)},!0):(i=$(`<div class="pg-tutorial-video-overlay black" style="opacity:0;"><div class="pg-tutorial-video-wrapper">
<div class="pg-tutorial-video-iframe-box">
    <iframe src="${o}" frameborder="0" allow="autoplay; fullscreen" allowfullscreen ${""}></iframe>
    </div>
    <div class="pg-video-text">
        <div class="pg-video-commands">
            <i class="close-video icon icon-close" title="Close the video."></i>
            <i class="show-text icon icon-align-left" title="Show / hide the video text."></i>
            <i class="make-thumb icon icon-window" title="Pause and make smaller."></i>
        </div>
        <div class="pg-video-text-title"><h2>Video text</h2><p>Click on the text to play or pause that part.</p></div>
        <div class="pg-video-text-content"></div>
        </div>
    </div>
<div class="pg-tutorial-video-thumb-overlay"></div>
</div>`),addTooltip(i.find(".pg-video-commands i"),"",{placement:"left"}),o=i.find(".pg-video-text-content"),a=i.find(".pg-tutorial-video-wrapper"),t?(n="",t.split("\n\n").forEach(function(e){var t,i;e.length&&(i=(t=e.split("\n"))[1].match(/(\d\d):(\d\d):([0-9,]+)/),i=3600*parseInt(i[1])+60*parseInt(i[2])+parseFloat(i[3]),t.shift(),t.shift(),n+=`<p data-time="${i}">${t.join(" ")}</p>`)}),o.html(n)):(a.removeClass("expanded"),i.find(".show-text").hide()),i.appendTo($("body")),gsap.to(i.get(0),{opacity:1,duration:.5}),"1"===pinegrow.getSetting("video-player-text","1")&&t&&a.addClass("expanded"),i.find(".close-video").on("click",function(e){e.preventDefault(),v()}),i.find(".show-text").on("click",function(e){e.preventDefault(),a.toggleClass("expanded"),pinegrow.setSetting("video-player-text",a.hasClass("expanded")?"1":"0")}),i.find(".make-thumb, .pg-tutorial-video-thumb-overlay").on("click",function(e){e.preventDefault(),i.toggleClass("thumb")}),d=[],o.find("[data-time]").each(function(e,t){var i=parseFloat(t.getAttribute("data-time"));d.push({start:i,end:0,el:t}),0<e&&(d[e-1].end=i)}),0<d.length&&(d[d.length-1].end=9999999),l=i.find("iframe"),s=function(e){l.get(0).contentWindow.postMessage(e,"*")},r=function(e){"video_timeupdate"===e.data.action?f(parseFloat(e.data.data.seconds)):"video_ended"!==e.data.action||u||v(1)},m&&window.addEventListener("message",r),o.on("click","[data-time]",function(e){var t;e.preventDefault(),this.classList.contains("current")?m?s({action:"toggle"}):p.getPaused().then(function(e){e?p.play():p.pause()}):(t=parseFloat(this.getAttribute("data-time")),m?s({action:"seek",time:t}):p.setCurrentTime(t).then(function(){p.play()}))}),p=m?null:new Vimeo.Player(i.find("iframe").get(0)),c=null,v=function(e){m?(window.removeEventListener("message",r),s({action:"destroy"})):(p.off("timeupdate"),p.off("ended")),gsap.to(i.get(0),{opacity:0,duration:.5,delay:e||0,onComplete:function(){i.find("iframe").attr("src","about:blank"),i.remove(),p=null}}),d=null},u=!1,m||p.on("ended",function(e){u||v(1)}),f=function(e){for(var t,i=null,o=0;o<d.length;o++)if(d[o].start<=e&&d[o].end>e){i=d[o];break}c!==i&&(c&&c.el.classList.remove("current"),i&&(i.el.classList.add("current"),t=$(i.el),pgScrollToItemInContainer(t,t.parent(),!1,750,null,0)),c=i)},m||p.on("timeupdate",function(e){var t=parseFloat(e.seconds);f(t)}))};